apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: rpe
 namespace: rpe
spec:
 type: 0
 ResourceID: /subscriptions/TODO/resourceGroups/managed-identities-prod-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rpe-prod-mi
 ClientID: TODO

---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: rpe-binding
  namespace: rpe
spec:
  AzureIdentity: rpe
  Selector: rpe
