---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: data-extractor-job-demo
  namespace: software-engineering
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.job: glob:prod-*
spec:
  releaseName: data-extractor-job
  chart:
    repository: https://hmcts.azurecr.io/helm/v1/repo/
    name: data-extractor-job
    version: 0.0.3
  valueFileSecrets:
  - name: "data-extractor-values"
  values:
    job:
      image: hmcts.azurecr.io/hmcts/data-extractor-job:prod-2ad488af
      suspend: true
      aadIdentityName: mi
      keyVaults:
        "data-extractor":
          resourceGroup: data-extractor
          secrets:
          - aat-ccdro-user
          - aat-ccdro-password
      labels:
        app.kubernetes.io/instance: data-extractor-job-demo
        app.kubernetes.io/name: data-extractor-job
      schedule: "* 2 * * *"
      environment:
        ETL_DB_URL: jdbc:postgresql://ccd-data-store-api-postgres-db-aat.postgres.database.azure.com:5432/ccd_data_store
        ETL_DB_USER_FILE: data-extractor/aat-ccdro-user
        ETL_DB_PASSWORD_FILE: data-extractor/aat-ccdro-password
        ETL_SQL: >
          SELECT id, case_type_id, case_type_version, data
          FROM case_event
          WHERE created_date >= (current_date-1 + time '00:00')
          AND created_date < (current_date + time '00:00')
          ORDER BY created_date ASC;
        ETL_ACCOUNT: etldemoaat
        ETL_CONTAINER: demoaat01
        ETL_FILE_TYPE: jsonlines
        ETL_FILE_PREFIX: demo01
        ETL_MSI_CLIENT_ID: 1461ff03-675c-423c-95a4-fb50d31254ff
    global:
      job:
        kind: CronJob
      subscriptionId: "1c4f0704-a29e-403d-b719-b90c34ef14c9"
      tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      environment: aat
