---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: draft-store-service
  namespace: rpe
spec:
  releaseName: draft-store-service
  chart:
    repository: https://hmcts.azurecr.io/helm/v1/repo/
    name: draft-store-service
    version: 1.0.3
  values:
    java:
      image: hmcts.azurecr.io/hmcts/draft-store-service:prod-fa081538
      ingressHost: draft-store-service.service.core-compute-sandbox.internal
      aadIdentityName: rpe
      environment:
        DRAFT_STORE_DB_CONN_OPTIONS: ?sslmode=require
        DRAFT_STORE_DB_NAME: draftstore
        DRAFT_STORE_DB_PORT: '5432'
        RUN_DB_MIGRATION_ON_STARTUP: 'false'
        SPRING_APPLICATION_NAME: "HMCTS Draft Store AKS"
      keyVaults:
        "draft-store":
          resourceGroup: draft-store-service
          secrets:
          - service-POSTGRES-PASS