apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: mi-sbox
 namespace: mi-sbox
spec:
 type: 0
 ResourceID: /subscriptions/0c1744f8-9e63-4742-9c28-c066fd2e6eee/resourcegroups/managed-identities-mi-sbox-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-sbox-mi
 ClientID: c786c9a0-3dc1-41bd-9a6a-13cdc28b33ac
---

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: mi-binding
  namespace: mi-sbox
spec:
  AzureIdentity: mi
  Selector: mi

